name = "replr-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
FREE_DAILY_LIMIT = "20"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "4bdb1c9ad31f40dda0898c86b8472234"

[[routes]]
pattern = "api.replr.app/*"
zone_name = "replr.app"
